### ISSUE TITLE
User can create items

### ISSUE THREAD

**Issue by MMaus** [MMaus/zettelfix#12]
As user
I want to be able to create shopping items
So that I can use them on my shopping list

# Tasks

- design a consistent view for items, shops and shelfs: are they listed alphabetically in independent manner, or are they listed within their respective parent(s)?
- proposition: "Top level items" of views (Shops, Shelves) are displayed alphabetically. Within each, the children are listed alphabetically

# AC:

- [ ] ~~The item view display an ordered list of shelves~~
- [x] There is a (floating / fixed / action ?) button to create new items
- [x] This button opens a "create item" dialog
- [x] In the "create item" dialog, there is a multiple choice dropdown of shelves to which to add the item.
- [x] No selected shelf is OK, but results in a warning.
- [x] User has a button to add the new item to the selected shelves (Enter also works)
