### ISSUE TITLE
EPIC: Manage items

### ISSUE THREAD

**Issue by MMaus** [MMaus/zettelfix#13]
- [x] #12
- [ ] User can assign and remove items to / from shelves
- [ ] User can assign and remove shelves to / from shops
- [ ] User can manage orphaned shelves and items

**Comment by MMaus** [comment]
Tracked as Milestone
